name: GitHub Practice Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display a message
        run: echo "Hello! GitHub Actions is running successfully."

      - name: Show current directory
        run: pwd

      - name: List repository files
        run: ls -la
